from rest_framework import serializers
from swasthGarbhApp.models import *
from cvd_portal.serializers import DynamicFieldsModelSerializer
from django.contrib.auth.models import User

# class PregenancyPatientsData(DynamicFieldsModelSerializer):


class MedicineSerializer(DynamicFieldsModelSerializer):
    patient_id = serializers.PrimaryKeyRelatedField(
        queryset=Patient.objects.all())
    medicines = serializers.SerializerMethodField('get_medicines_data')

    class Meta:
        model = Medicine
        fields = [
            'pk',
            'patient_id',
            'medicines'
        ]

    def get_medicines_data(self, obj):
        qset = Medicine.objects.filter(patient_id=obj.pk)
        ser = MedicinePerPatientSerialzier(qset, many=True, read_only=True)
        return ser.data


class MedicinePerPatientSerialzier(DynamicFieldsModelSerializer):

    class Meta:
        model = Medicine
        fields = [
            'pk',
            'patient_id',
            'medicine_name',
            'medicine_freq',
            'medicine_extra_comments',
            'medicine_start',
            'medicine_end',
            'medicine_Image',
            'isSOS'
        ]


class HospitalSerializer(DynamicFieldsModelSerializer):
    patient_id = serializers.PrimaryKeyRelatedField(
        queryset=Patient.objects.all())

    class Meta:
        model = Hospital
        fields = [
            'pk',
            'patient_id',
            'xCoordinate',
            'yCoordinate'
        ]


class ComplicationSerializer(DynamicFieldsModelSerializer):
    patient_id = serializers.PrimaryKeyRelatedField(
        queryset=Patient.objects.all())

    class Meta:
        model = Complication
        fields = [
            'pk',
            'informationByDoc',
            'patient_id',
            'complicationImage',
            'tookAction',
            'informationByPatient'
        ]


class ComplicationPerPatientSerializer(DynamicFieldsModelSerializer):
    class Meta:
        model = Complication
        fields = [
            'pk',
            'informationByDoc',
            'complicationImage',
            'tookAction',
            'informationByPatient'
        ]


class PregenancySerializer(DynamicFieldsModelSerializer):

    medicines = serializers.SerializerMethodField('get_medicines_data')
    complications = serializers.SerializerMethodField('get_complications_data')

    class Meta:
        model = PregnancyData
        fields = [
            'invest_chronic_hyper',
            'invest_type_2_diabetes',
            'invest_RHD_native',
            'invest_RHD_post',
            'invest_acyanotic',
            'invest_cyanotic',
            'invest_chronic_liver',
            'invest_chronic_kidney',
            'invest_APLA',
            'invest_SLE',
            'pk',
            'patient_id',
            'startDate',
            'medicines',
            'complications',
            'anc_1',
            'anc1_diabtese',
            'anc1_anemia',
            'anc1_hiv',
            'anc1_ultrasound',
            'anc1_tetnus',
            'anc1_urine',
            'anc_2',
            'anc2_diabtese',
            'anc2_anemia',
            'anc_3',
            'anc3_diabtese',
            'anc3_anemia',
            'anc3_urine',
            'anc_4',
            'anc4_diabtese',
            'anc_5',
            'anc5_diabtese',
            'anc5_urine',
            'anc_6',
            'anc6_diabtese',
            'anc6_anemia',
            'anc_7',
            'anc7_diabtese',
            'anc_8',
            'anc8_diabtese',
            'anc1_his_fever',
            'anc1_his_rash',
            'anc1_his_nausea_vomit',
            'anc1_his_bleed',
            'anc1_his_abdpain',
            'anc1_drugin',
            'anc1_his_smoke',
            'anc1_his_alcohol',
            'anc1_his_tob',
            'anc1_his_caff',
            'anc1_his_int',
            'anc1_exam_pallor',
            'anc1_exam_lcterus',
            'anc1_exam_clubbing',
            'anc1_exam_cyanosis',
            'anc1_exam_edem',
            'anc1_exam_lymp',
            'anc1_invest_HIV',
            'anc1_invest_hbsag',
            'anc1_invest_VDRL',
            'anc1_invest_urineRM',
            'anc1_invest_urineCS',
            'anc1_invest_CRL',
            'anc1_invest_NT',
            'anc1_invest_centile',
            'anc1_invest_text',
            'anc1_advice_Tfolate',
            'anc1_advice_TFe',
            'anc1_general_TSH',
            'anc1_general_T_nitro',
            'anc1_general_syp',
            'anc1_general_Tvit',
            'anc1_general_plenty',
            'anc2_his_breath',
            'anc2_his_fatigue',
            'anc2_his_head',
            'anc2_his_bleed',
            'anc2_his_burn',
            'anc2_his_quick_percieve',
            'anc2_exam_pallor',
            'anc2_exam_pedal',
            'anc2_exam_pa',
            'anc_2_pa_2weeks',
            'anc2_invest_quad',
            'anc2_invest_fetal',
            'anc2_advice_OGTT',
            'anc2_advice_TFe',
            'anc2_advice_TCa',
            'anc2_advice_Hb_Talb',
            'anc2_advice_Hb_TFe',
            'anc2_advice_Hb_HPLC',
            'anc2_advice_Hb_peri',
            'anc2_advice_Hb_serum',
            'anc2_advice_tetanus',
            'anc3_his_breath',
            'anc3_his_fatigue',
            'anc3_his_head',
            'anc3_his_bleed',
            'anc3_his_leak',
            'anc3_his_burn',
            'anc3_his_fetal_move',
            'anc3_his_itching',
            'anc3_exam_pallor',
            'anc3_exam_pedal',
            'anc3_exam_pa',
            'anc_3_pa_2weeks',
            'anc3_invest_GTT_fast',
            'anc3_invest_GTT_1hr',
            'anc3_invest_GTT_2hr',
            'anc3_invest_CBC',
            'anc3_invest_urine',
            'anc3_invest_ICT',
            'anc3_advice_TFe',
            'anc3_advice_DFMC',
            'anc3_advice_BleedPV',
            'anc3_advice_spotPV',
            'anc3_advice_leakPV',
            'anc3_advice_fetalmove',
            'anc3_advice_abdpain',
            'anc3_advice_injAntiD',
            'anc4_his_breath',
            'anc4_his_fatigue',
            'anc4_his_head',
            'anc4_his_bleed',
            'anc4_his_burn',
            'anc4_his_fetal_move',
            'anc4_his_itching',
            'anc4_exam_pallor',
            'anc4_exam_pedal',
            'anc4_exam_pa',
            'anc_4_pa_2weeks',
            'anc4_advice_TFe',
            'anc4_advice_TCa',
            'anc4_advice_DFMC',
            'anc4_advice_BleedPV',
            'anc4_advice_spotPV',
            'anc4_advice_leakPV',
            'anc4_advice_fetalmove',
            'anc4_advice_abdpain',
            'anc4_advice_injAntiD',
            'anc4_advice_USG',
            'anc5_his_breath',
            'anc5_his_fatigue',
            'anc5_his_head',
            'anc5_his_bleed',
            'anc5_his_burn',
            'anc5_his_fetal_move',
            'anc5_his_itching',
            'anc5_his_vaginal_del',
            'anc5_his_LSCS_del',
            'anc5_his_birth_attendant',
            'anc5_exam_pallor',
            'anc5_exam_pedal',
            'anc5_exam_pa',
            'anc_5_pa_2weeks',
            'anc5_invest_CBC',
            'anc5_invest_LFT',
            'anc5_invest_KFT',
            'anc5_invest_CPR',
            'anc5_advice_DFMC',
            'anc5_advice_TFe_Ca',
            'anc5_advice_BleedPV',
            'anc5_advice_spotPV',
            'anc5_advice_leakPV',
            'anc5_advice_fetalmove',
            'anc5_advice_abdpain',
            'anc5_advice_NST',
            'anc6_his_breath',
            'anc6_his_fatigue',
            'anc6_his_head',
            'anc6_his_bleed',
            'anc6_his_burn',
            'anc6_his_fetal_move',
            'anc6_his_itching',
            'anc6_exam_pallor',
            'anc6_exam_pedal',
            'anc6_exam_pa',
            'anc6_pa_2weeks',
            'anc6_advice_DFMC',
            'anc6_advice_TFe_Ca',
            'anc6_advice_BleedPV',
            'anc6_advice_spotPV',
            'anc6_advice_leakPV',
            'anc6_advice_fetalmove',
            'anc6_advice_abdpain',
            'anc6_advice_NST',
            'anc7_his_breath',
            'anc7_his_fatigue',
            'anc7_his_head',
            'anc7_his_bleed',
            'anc7_his_burn',
            'anc7_his_fetal_move',
            'anc7_his_itching',
            'anc7_exam_pallor',
            'anc7_exam_pedal',
            'anc7_exam_pa',
            'anc7_pa_2weeks',
            'anc7_advice_DFMC',
            'anc7_advice_TFe_Ca',
            'anc7_advice_BleedPV',
            'anc7_advice_spotPV',
            'anc7_advice_leakPV',
            'anc7_advice_fetalmove',
            'anc7_advice_abdpain',
            'anc8_his_breath',
            'anc8_his_fatigue',
            'anc8_his_head',
            'anc8_his_bleed',
            'anc8_his_burn',
            'anc8_his_fetal_move',
            'anc8_his_itching',
            'anc8_exam_pallor',
            'anc8_exam_pedal',
            'anc8_exam_pa',
            'anc8_advice_DFMC',
            'anc8_advice_Fe_Ca',
            'anc8_advice_induction',
            'invest_others',
            'invest_drug_history',
            'anc_1_POG',
            'anc_1_date',
            'anc1_his_others',
            'anc1_exam_height',
            'anc1_exam_weight',
            'anc1_exam_BMI',
            'anc1_exam_PR',
            'anc1_exam_BP',
            'anc1_exam_RR',
            'anc1_exam_temp',
            'anc1_exam_proteinuria',
            'anc1_exam_chest',
            'anc1_exam_PA',
            'anc1_exam_others',
            'anc1_invest_bg',
            'anc1_invest_husband_bg',
            'anc1_invest_hemo',
            'anc1_invest_bloodsugar_fast',
            'anc1_invest_bloodsugar_post',
            'anc1_invest_GTT_fast',
            'anc1_invest_GTT_1hr',
            'anc1_invest_GTT_2hr',
            'anc1_invest_TSH',
            'anc1_invest_NT_done',
            'anc1_invest_PAPP',
            'anc1_invest_b_hcg',
            'anc1_invest_levelII_done',
            'anc1_invest_normal',
            'anc1_invest_others',
            'anc1_general_nutritional',
            'anc1_general_ailment',
            'anc1_general_ICT',
            'anc1_general_others',
            'anc2_POG',
            'anc2_his_others',
            'anc2_exam_PR',
            'anc2_exam_BP',
            'anc2_exam_weight',
            'anc2_exam_others',
            'anc2_invest_others',
            'anc2_advice_nutri',
            'anc2_advice_general',
            'anc2_advice_common',
            'anc2_advice_others',
            'anc3_his_others',
            'anc3_exam_PR',
            'anc3_exam_BP',
            'anc3_exam_weight',
            'anc3_exam_others',
            'anc3_advice_nutri',
            'anc3_advice_general',
            'anc3_advice_common',
            'anc3_advice_others',
            'anc4_his_others',
            'anc4_exam_PR',
            'anc4_exam_BP',
            'anc4_exam_weight',
            'anc4_exam_others',
            'anc4_advice_nutri',
            'anc4_advice_general',
            'anc4_advice_common',
            'anc4_advice_others',
            'anc5_his_others',
            'anc5_his_timing',
            'anc5_exam_BP',
            'anc5_exam_weight',
            'anc5_exam_others',
            'anc5_invest_others',
            'anc5_USG_BPD_cm',
            'anc5_USG_BPD_weeks',
            'anc5_USG_BPD_centile',
            'anc5_USG_HC_cm',
            'anc5_USG_HC_weeks',
            'anc5_USG_HC_centile',
            'anc5_USG_AC_cm',
            'anc5_USG_AC_weeks',
            'anc5_USG_AC_centile',
            'anc5_USG_FL_cm',
            'anc5_USG_FL_weeks',
            'anc5_USG_FL_centile',
            'anc5_USG_EFW_gm',
            'anc5_USG_EFW_weeks',
            'anc5_USG_EFW_centile',
            'anc5_USG_liquor_SLP',
            'anc5_USG_liquor_AFI',
            'anc5_USG_UAPI',
            'anc5_USG_UAPI_centile',
            'anc5_USG_MCAPI',
            'anc5_USG_MCAPI_centile',
            'anc5_advice_nutri',
            'anc5_advice_general',
            'anc5_advice_common',
            'anc5_advice_others',
            'anc5_USG_EFW_weeks',
            'anc5_USG_EFW_centile',
            'anc6_his_others',
            'anc6_exam_PR',
            'anc6_exam_BP',
            'anc6_exam_weight',
            'anc6_exam_others',
            'anc6_exam_pelvic',
            'anc6_advice_others',
            'anc7_his_others',
            'anc7_exam_PR',
            'anc7_exam_BP',
            'anc7_exam_weight',
            'anc7_exam_others',
            'anc7_advice_others',
            'anc8_his_others',
            'anc8_exam_PR',
            'anc8_exam_BP',
            'anc8_exam_weight',
            'anc8_exam_others',
            'anc8_advice_others'
        ]

    def get_medicines_data(self, obj):
        qset = Medicine.objects.filter(patient_id=obj.pk)
        ser = MedicinePerPatientSerialzier(qset, many=True, read_only=True)
        return ser.data

    def get_complications_data(self, obj):
        qset = Complication.objects.filter(patient_id=obj.pk)
        ser = ComplicationPerPatientSerializer(qset, many=True, read_only=True)
        return ser.data
