# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvd_portal', '0016_auto_20180225_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='anc1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabtese', models.BooleanField(default=0)),
                ('anemia', models.BooleanField(default=0)),
                ('hiv', models.BooleanField(default=0)),
                ('ultrasound', models.BooleanField(default=0)),
                ('tetnus', models.BooleanField(default=0)),
                ('urine', models.BooleanField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsInAnc1', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='anc2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabtese', models.BooleanField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsInAnc7', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='anc3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabtese', models.BooleanField(default=0)),
                ('anemia', models.BooleanField(default=0)),
                ('urine', models.BooleanField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsInAnc3', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='anc4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabtese', models.BooleanField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsInAnc4', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='anc5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabtese', models.BooleanField(default=0)),
                ('urine', models.BooleanField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsInAnc5', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='anc6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabtese', models.BooleanField(default=0)),
                ('anemia', models.BooleanField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsInAnc6', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='anc8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabtese', models.BooleanField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsInAnc8', to='cvd_portal.Patient')),
            ],
        ),
    ]
