# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 12:13
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0016_auto_20180225_1455'),
        ('swasthGarbhApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anc7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabtese', models.BooleanField(default=0)),
                ('dueDate', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('safeDate', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsInAnc7', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Complication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informationByDoc', models.TextField()),
                ('complicationImage', models.TextField()),
                ('tookAction', models.BooleanField(default=0)),
                ('informationByPatient', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsComplication', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xCoordinate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('yCoordinate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsPregHospitals', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_Image', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsMedicine', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Pregenancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsPreg', to='cvd_portal.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='anc1',
            name='dueDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc1',
            name='safeDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc2',
            name='anemia',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='anc2',
            name='dueDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc2',
            name='safeDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc3',
            name='dueDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc3',
            name='safeDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc4',
            name='dueDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc4',
            name='safeDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc5',
            name='dueDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc5',
            name='safeDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc6',
            name='dueDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc6',
            name='safeDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc8',
            name='dueDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anc8',
            name='safeDate',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='anc2',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsInAnc2', to='cvd_portal.Patient'),
        ),
    ]
