# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0002_auto_20180620_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregenancy',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
