# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0003_auto_20180620_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anc1',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='anc2',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='anc3',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='anc4',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='anc5',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='anc6',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='anc7',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='anc8',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='complication',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
