# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0004_auto_20180620_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anc6',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientsInAnc6', to='cvd_portal.Patient', unique=True),
        ),
    ]
