# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 17:59
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0016_auto_20180225_1455'),
        ('swasthGarbhApp', '0006_auto_20180620_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urine_albumin', models.DecimalField(decimal_places=1, max_digits=1)),
                ('headache', models.BooleanField(default=0)),
                ('abdominal_pain', models.BooleanField(default=0)),
                ('visual_problems', models.BooleanField(default=0)),
                ('bleeding_per_vaginum', models.BooleanField(default=0)),
                ('decreased_fetal_movements', models.BooleanField(default=0)),
                ('swelling_in_hands_or_face', models.BooleanField(default=0)),
                ('time_stamp', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancyData', to='cvd_portal.Patient')),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='xCoordinate',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='yCoordinate',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
