# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-22 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0009_auto_20181022_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anc1',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='anc2',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='anc3',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='anc4',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='anc5',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='anc6',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='anc7',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='anc8',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='pregenancy',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='anc1',
        ),
        migrations.DeleteModel(
            name='anc2',
        ),
        migrations.DeleteModel(
            name='anc3',
        ),
        migrations.DeleteModel(
            name='anc4',
        ),
        migrations.DeleteModel(
            name='anc5',
        ),
        migrations.DeleteModel(
            name='anc6',
        ),
        migrations.DeleteModel(
            name='Anc7',
        ),
        migrations.DeleteModel(
            name='anc8',
        ),
        migrations.DeleteModel(
            name='Pregenancy',
        ),
    ]
