# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-22 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0010_auto_20181022_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnancydata',
            old_name='patient_id',
            new_name='pId',
        ),
    ]
