# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-22 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0011_auto_20181022_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnancydata',
            old_name='pId',
            new_name='patient_id',
        ),
    ]
