# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-22 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0012_auto_20181022_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregnancydata',
            name='id',
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cvd_portal.Patient'),
        ),
    ]
