# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 16:12
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0013_auto_20181022_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_period',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_time_of_day',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_timespan_days',
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_end',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_freq',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_start',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
    ]
