# Generated by Django 2.1.5 on 2019-05-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0020_auto_20190519_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnancydata',
            old_name='anc4_advice_TCa',
            new_name='anc4_advice_Tca',
        ),
    ]
