# Generated by Django 2.1.5 on 2019-05-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0021_auto_20190519_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnancydata',
            old_name='anc4_advice_Tca',
            new_name='anc4_advice_TCa',
        ),
    ]
