# Generated by Django 2.1.5 on 2019-05-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0023_auto_20190522_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_his_others',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_1_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
