# Generated by Django 2.1.5 on 2019-05-23 10:51

import cvd_portal.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0025_auto_20190522_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_1_date',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
    ]
