# Generated by Django 2.1.5 on 2019-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0026_auto_20190523_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_1_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
